#!/usr/bin/lua

-- This is 312-gluon-client-bridge-wireless-ffgt. It is supposed
-- to run instead of 320-gluon-client-bridge-wireless ...
-- This means we will need to do dirty tricks here during build :(

local site = require 'gluon.site_config'
local util = require 'gluon.util'

local uci = require('luci.model.uci').cursor()


local function is_disabled(config, name)
  local disabled = config and config.disabled
  if uci:get('wireless', name) then
    disabled = uci:get_bool('wireless', name, 'disabled')
  end

  return disabled and 1 or 0
end

local function is_cfgdisabled(config, name)
  local disabled = config and config.disabled
  if uci:get('wireless', name) then
    disabled = uci:get_bool('wireless', name, 'cfgdisabled')
  end

  return disabled and 1 or 0
end

local function is_nachtruhe(config, name)
  local disabled = config and config.disabled
  if uci:get('wireless', name) then
    disabled = uci:get_bool('wireless', name, 'nachtruhe')
  end

  return disabled and 1 or 0
end


local function configure_client(config, radio, index, suffix)
  local name = 'client_' .. radio
  local disabled = is_disabled(config, name)
  local cfgdisabled = is_cfgdisabled(config, name)
  local nachtruhe = is_nachtruhe(config, name)

  uci:delete('wireless', name)

  if not config then
    return
  end

  local macaddr = util.get_wlan_mac(radio, index, 1)
  if not macaddr then
    return
  end

  uci:section('wireless', 'wifi-iface', name,
    {
      device = radio,
      network = 'client',
      mode = 'ap',
      ssid = config.ssid,
      macaddr = macaddr,
      ifname = suffix and 'client' .. suffix,
      disabled = disabled,
      cfgdisabled = cfgdisabled,
      nachtruhe = nachtruhe,
    }
  )
end

local function configure_radio(radio, index, config)
  local suffix = radio:match('^radio(%d+)$')

  configure_client(config.ap, radio, index, suffix)
end

util.iterate_radios(configure_radio)

uci:save('wireless')
