#!/bin/sh /etc/rc.common
#exit 0

# if enabled ("exit 0" above removed), if site_selectcode is missing,
# force geolocating the node. This is for updating pre-siteselect nodes,
# since we can't query this info anyhow outside config mode.
#
# Principle: get started from cron every n (30) minutes. If no coordinates
# present, force geolocation via WiFi. If coordinates are present and
#  /tmp/needs_rgeo is set, try to map coordinates to an address (which in
# turn defines the sitecode).
#
# If running for more than 2 hours, allow rebooting again (see below).
#
# If we have a sitecode, disarm the cron job, smile and be happy.
#
# In case we don't have a sitecode yet, flag "rgeo needed".
#
# If we have a new sitecode, update system, prevent us from entering a reboot loop
# and reboot.

START=99

# This should return the locode or "none". "none" won't match any valid locode,
# as locode is only 3 characters ;)
curcommunity=`/usr/bin/lua -e "local site=require 'gluon.site_config' local curcommunity=site.site_selectcode or 'none' print (curcommunity)"`

curlat="`/sbin/uci get gluon-node-info.@location[0].longitude 2>/dev/null`"
RClat=$?
locode="`/sbin/uci get gluon-node-info.@location[0].locode 2>/dev/null`"
RCloc=$?
if [ $RClat -eq 1 -o $RCloc -eq 1 ]; then
  logger '$0: Forcing gelococation due to missing coordinates/locode'
  /lib/gluon/ffgt-geolocate/senddata.sh --force
  /bin/rm -f /tmp/needs_rgeo
else
  if [ -e /tmp/needs_rgeo ]; then
    /lib/gluon/ffgt-geolocate/rgeo.sh
    /bin/rm -f /tmp/needs_rgeo
  fi
fi

uptime=`/usr/bin/awk </proc/uptime 'BEGIN{uptime=0;} {uptime=sprintf("%d", $1);} END{print uptime;}'`
if [ $uptime -gt 7200 ]; then
  rebootloopprevention="`/sbin/uci get gluon-node-info.@location[0].rebootloopprevention 2>/dev/null`"
  if [ "X${rebootloopprevention}" != "X" ]; then
    /sbin/uci delete gluon-node-info.@location[0].rebootloopprevention
    /sbin/uci commit
  fi
fi

newcommunity="`/sbin/uci get gluon-node-info.@location[0].siteselect 2>/dev/null`"
locode="`/sbin/uci get gluon-node-info.@location[0].locode 2>/dev/null`"

if [ "X${locode}" != "X" -a "X${newcommunity}" != "X" -a "X${curcommunity}" != "X" ]; then
  # All set ... Consistency check.
  if [ "${newcommunity}" == "${curcommunity}" -a "X${locode}" != "X" ]; then
    # newcommunity == currcommunity, non-empty locode, excellent! Stop the cron job ...
    /bin/sed -i -e 's%^.*$%#&%g' /usr/lib/micron.d/siteselect
    rebootloopprevention="`/sbin/uci get gluon-node-info.@location[0].rebootloopprevention 2>/dev/null`"
    if [ "X${rebootloopprevention}" != "X" ]; then
      /sbin/uci delete gluon-node-info.@location[0].rebootloopprevention
      /sbin/uci commit
    fi
  fi
fi

if [ "X${locode}" == "X" ]; then
  # Missing. Try to fix via rgeo call on next run via cron
  touch /tmp/needs_rgeo
fi

if [ "X${newcommunity}" == "X" ]; then
  # siteselect isn't there, shouldn't happen. Bail out for now.
  logger 'Whow, siteselect not set? This should never happen ...'
  exit 0
fi

if [ "${newcommunity}" != "${curcommunity}" ]; then
  # Installed site.json does not align with (new) siteselect code.
  # Just for completeness, sync.
  srcfile="`/sbin/uci get siteselect.${newcommunity}.path`"
  /bin/cp ${srcfile} /lib/gluon/site.json
  /lib/gluon/site-upgrade
  rebootloopprevention="`/sbin/uci get gluon-node-info.@location[0].rebootloopprevention 2>/dev/null`"
  if [ "X${rebootloopprevention}" == "X" ]; then
    /sbin/uci set gluon-node-info.@location[0].rebootloopprevention='1'
    /sbin/uci commit
    ## Reboot into new config in 10 seconds ...
    ((sleep 10 ; /sbin/reboot -f)&)
  fi
fi
